version: "3.8"

networks:
  app-database_app-network:
    external: true

services:
  app-backend:
    container_name: app-laravel-api
    build:
      context: ./
      dockerfile: ./app/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./app/api:/var/www/html:delegated
    restart: unless-stopped
    networks:
      app-database_app-network:
        ipv4_address: 172.30.0.22

  web-server:
    container_name: app-nginx-server
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - 30002:80
    volumes:
      - ./app/api:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app-backend
    restart: unless-stopped
    networks:
      app-database_app-network:
        ipv4_address: 172.30.0.23