version: "3.8"

networks:
  app-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24

services:
  mysql_db:
    container_name: app-mysql-db-cluster
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app-app
    ports:
      - 30000:3306
    restart: unless-stopped
    volumes:
      - ./data/mysql:/var/lib/mysql
    networks:
      app-network:
        ipv4_address: 172.30.0.20

  phpmyadmin:
    container_name: app-phpmyadmin
    image: phpmyadmin:latest
    ports:
      - 30001:80
    environment:
      - PMA_ARBITRARY=1
    restart: unless-stopped
    networks:
      app-network:
        ipv4_address: 172.30.0.21