version: "3.8"

networks:
  app-database_app-network:
    external: true

services:
  app-react:
    container_name: react
    build:
      context: ./
      dockerfile: ./app/react/Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./app/react:/var/www/html:delegated
    ports:
      - 30003:5173
    restart: unless-stopped
    networks:
      app-database_app-network:
        ipv4_address: 172.30.0.24